"""Scenario parser subsystem contracts."""

from .contracts import (
    JsonObject,
    JsonScalar,
    JsonValue,
    ParseDiagnostic,
    ParseDiagnosticKind,
    ParseDiagnosticSeverity,
    ScenarioParseError,
    ScenarioParseOptions,
    ScenarioParseResult,
    ScenarioParser,
    ScenarioParsingError,
    SourceLocation,
    empty_json_object,
    empty_parse_diagnostics,
)
from .markdown import (
    LineSpan,
    MarkdownBackend,
    MarkdownBlock,
    MarkdownBlockKind,
    MarkdownItBackend,
    MarkdownScenarioDocument,
    MarkdownSection,
    MarkdownTokenDocument,
    parse_markdown_document_from_backend,
)
from .source import ScenarioSource, load_scenario_source
from .steps import MARKDOWN_STEP_RE, ParsedStepDraft, StepBlock, StepFieldKind, StepFieldValue, StepFields, parse_step_block, split_step_blocks
from .variables import ParsedVariable, VariableParseResult, parse_variables_section

__all__ = [
    "JsonObject",
    "JsonScalar",
    "JsonValue",
    "LineSpan",
    "MarkdownBackend",
    "MarkdownBlock",
    "MarkdownBlockKind",
    "MarkdownItBackend",
    "ParseDiagnostic",
    "ParseDiagnosticKind",
    "ParseDiagnosticSeverity",
    "ParsedVariable",
    "ScenarioParseError",
    "ScenarioParseOptions",
    "ScenarioParseResult",
    "ScenarioParser",
    "ScenarioParsingError",
    "ScenarioSource",
    "SourceLocation",
    "MARKDOWN_STEP_RE",
    "MarkdownScenarioDocument",
    "MarkdownSection",
    "MarkdownTokenDocument",
    "ParsedStepDraft",
    "StepBlock",
    "StepFieldKind",
    "StepFieldValue",
    "StepFields",
    "VariableParseResult",
    "empty_json_object",
    "empty_parse_diagnostics",
    "load_scenario_source",
    "parse_markdown_document_from_backend",
    "parse_step_block",
    "parse_variables_section",
    "split_step_blocks",
]
