"""Domain contracts for generation pipeline inputs, plans, and traceability."""

from .contracts import GenerationArtifactStore
from .models import (
    AgentPlannedTestCaseInput,
    AgentTestPlanInput,
    DiagnosticSeverity,
    GapCategory,
    GenerationDiagnostic,
    GenerationRunContext,
    GenerationSourceInput,
    NormalizedProseSource,
    NormalizedTestPlan,
    PlannedCaseSupport,
    PlannedCaseGap,
    PlannedRouteIntent,
    PlannedTestCase,
    ProseTestCaseDraft,
    RouteSupportHint,
    SourceInputFormat,
    TraceabilityLink,
    TraceabilityMap,
)

__all__ = [
    "AgentPlannedTestCaseInput",
    "AgentTestPlanInput",
    "DiagnosticSeverity",
    "GapCategory",
    "GenerationArtifactStore",
    "GenerationDiagnostic",
    "GenerationRunContext",
    "GenerationSourceInput",
    "NormalizedProseSource",
    "NormalizedTestPlan",
    "PlannedCaseSupport",
    "PlannedCaseGap",
    "PlannedRouteIntent",
    "PlannedTestCase",
    "ProseTestCaseDraft",
    "RouteSupportHint",
    "SourceInputFormat",
    "TraceabilityLink",
    "TraceabilityMap",
]
